//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VlasProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalibleResources
    {
        public int IDResouce { get; set; }
        public int Quantity { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
