//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VlasProg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryEntities : DbContext
    {
        public FactoryEntities()
            : base("name=FactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountType { get; set; }
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<AvalibleResources> AvalibleResources { get; set; }
        public virtual DbSet<OrderProd> OrderProd { get; set; }
        public virtual DbSet<OrderRes> OrderRes { get; set; }
        public virtual DbSet<ProdCategory> ProdCategory { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ResCategory> ResCategory { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<ResourceProduct> ResourceProduct { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
