//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VlasProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.OrderRes = new HashSet<OrderRes>();
            this.ResourceProduct = new HashSet<ResourceProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public int IDSupplier { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual AvalibleResources AvalibleResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRes> OrderRes { get; set; }
        public virtual ResCategory ResCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceProduct> ResourceProduct { get; set; }
    }
}
